### ISSUE TITLE
Criteria and metrics?

### ISSUE THREAD

**Issue by Hrxn** [selfagency/bs-detector#2]
Okay, I assume this extension exists because of the debate around questionable news sources shared on Facebook, right?

Good, but all it does is checking the site visited by the user against a list of domains.

Which leads us to the interesting question: what are the criteria and metrics that decide about a domain ending up on said list? The mechanism? The deciding factors taken into account? Where is the transparency in regard to this process? Are decisions final, or can they be challenged or appealed? Is there some official and reliable way in which arbitration is handled?

**Comment by selfagency** [comment]
check out the updated readme

**Comment by stevendelapena** [comment]
From the readme: "The list was compiled from various sources and consists chiefly of websites that traffic in fake news, parody news, unsourced claims, fabrications, innuendo, and conspiracy theory. I have done my absolute best to stay wholly objective and as such the entries span the political spectrum" What sources? If you want to be objective then list sources and let the community decide whether these sources are valid. I can tell you as a fact (because they sites state facts and source them), that quite a few of the sites listed do not represent any of those things you've claimed they are.

**Comment by Hrxn** [comment]
I guess that here "objective" simply means *according to my personal opinion*....

**Comment by selfagency** [comment]
Is anyone forcing you to use this plugin? Either help make it better by making meaningful and constructive suggestions for improvement or fuck right off.
