### ISSUE TITLE
USS Liberty Veterans Association websites should not be included

### ISSUE THREAD

**Issue by joemeadors** [selfagency/bs-detector#37]
http://www.usslibertyveterans.org and http://usslibertyveteransblog.org/ are official voices of the USS Liberty Veterans Association which is comprised of the officers and crew who served aboard the USS Liberty and should not be included in your database.

Thanks in advance.

Joe Meadors
USS Liberty Survivor
Director of Operations, USS Liberty Veterans Association
Email: joe@ussliberty.com

**Comment by Bastlynn** [comment]
Thank you for making us aware of this.

I think I can tell why it got added to the list. Given the attack involved and the countries involved in it, I suspect your site has been linked to by a lot of anti-Semite and conspiracy theory sites that may be using your experiences during service to make political hay. Which puts us in a tough spot here since addressing that political abuse of reality is what this work is about. And of course, there's no real way to stop people from using the attack on the Liberty for that purpose.

@selfagency has the final say at the moment. I suspect the best way to review this site will be to look through postings on the site (as opposed to postings *about* the site) with an eye towards getting a representative feel for the material found there.

@joemeadors if you could help us save some time on that review by providing links to a few of the site posts that you feel are representative of the site's day-to-day content that would make that effort go faster. Again, thank you for making us aware of this, and I look forward to seeing your response.

**Comment by ultramancool** [comment]
"Political abuse of reality" shouldn't be what this is about. Outright fake, garbage information, you know, _bullshit_ should probably be what a project called BS Detector is about.

**Comment by selfagency** [comment]
@joemeadors Your organization's website will be removed as it is not a news source.
