### ISSUE TITLE
Satire vs B.S.

### ISSUE THREAD

**Issue by wilsonehusin** [selfagency/bs-detector#7]
I saw the list of websites in the list and some of them are just satire websites instead of B.S. news (borowitzreport.com for example). I would suggest to say "this is a satire article" instead of saying it's B.S. straight up.

**Comment by selfagency** [comment]
Yes, in the next version I am going to break up the list into different categories with different messages for each.

**Comment by Bastlynn** [comment]
I like this feature a lot as well. :)

**Comment by tresrottn** [comment]
Agree. thebeaverton.com is also satire (Canadian humor, lol) They seemed pleased the addon considers their site questionable :D

**Comment by selfagency** [comment]
@hrxn @stevendelapena If you actually want to help instead of just talking shit about my initial methodology, see above. 👆🏻

**Comment by stevendelapena** [comment]
I merely suggested you cite your sources, since you claim that is a reason for putting these sites on a list. If you wanna be avoid the suggestion for transparency and be hypocritical about your approach - have at it. You are only contributing to the problem of truth and transparency you claim to care about.

**Comment by selfagency** [comment]
@stevendelapena The sources are myriad lists of fake news sites that have been compiled by others that I collected from around the web and merged together — I honestly can't even remember all of the ones I drew from. However, as noted above, I am currently in the process of going through each site individually, removing those which don't belong, and providing a categorization that explains the reason for a site's inclusion in the list. However, it is nonsense to claim that providing a warning about a site's reliability is comparable to willfully misleading people with the false information those sites contain.

**Comment by selfagency** [comment]
The JSON datafile and the ability to sort items by category is now integrated.

**Comment by stevendelapena** [comment]
Again, you write: " The sources are myriad lists of fake news sites that have been compiled by others " , just reference who "the others" are. If you are going to put a site on a list because they don't reference their sources, it would be hypocritical to not so the same. And I never made the claim about willfully misleading people. This would imply that ALL sites without references are willfully misleading people. I make no such claim or implication, but based on your response, you do. Which should be all the more reason to cite your sources so you don't fall into that bucket.
